export function useLanguages() {
    const languages = [
        { value: 'arabic', label: 'languages.arabic' },
        { value: 'bengali', label: 'languages.bengali' },
        { value: 'bulgarian', label: 'languages.bulgarian' },
        { value: 'chinese', label: 'languages.chinese' },
        { value: 'croatian', label: 'languages.croatian' },
        { value: 'czech', label: 'languages.czech' },
        { value: 'danish', label: 'languages.danish' },
        { value: 'dutch', label: 'languages.dutch' },
        { value: 'english', label: 'languages.english' },
        { value: 'finnish', label: 'languages.finnish' },
        { value: 'french', label: 'languages.french' },
        { value: 'gaelic', label: 'languages.gaelic' },
        { value: 'german', label: 'languages.german' },
        { value: 'greek', label: 'languages.greek' },
        { value: 'hebrew', label: 'languages.hebrew' },
        { value: 'hindi', label: 'languages.hindi' },
        { value: 'hungarian', label: 'languages.hungarian' },
        { value: 'icelandic', label: 'languages.icelandic' },
        { value: 'indonesian', label: 'languages.indonesian' },
        { value: 'italian', label: 'languages.italian' },
        { value: 'japanese', label: 'languages.japanese' },
        { value: 'korean', label: 'languages.korean' },
        { value: 'malay', label: 'languages.malay' },
        { value: 'norwegian', label: 'languages.norwegian' },
        { value: 'persian', label: 'languages.persian' },
        { value: 'polish', label: 'languages.polish' },
        { value: 'portuguese', label: 'languages.portuguese' },
        { value: 'romanian', label: 'languages.romanian' },
        { value: 'russian', label: 'languages.russian' },
        { value: 'serbian', label: 'languages.serbian' },
        { value: 'slovak', label: 'languages.slovak' },
        { value: 'spanish', label: 'languages.spanish' },
        { value: 'swahili', label: 'languages.swahili' },
        { value: 'swedish', label: 'languages.swedish' },
        { value: 'thai', label: 'languages.thai' },
        { value: 'turkish', label: 'languages.turkish' },
        { value: 'ukrainian', label: 'languages.ukrainian' },
        { value: 'vietnamese', label: 'languages.vietnamese' },
        { value: 'welsh', label: 'languages.welsh' }
    ];

    return languages;
}